# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1241043ae698bc42839cab3a40a7ede5165126f3689c2deb41d994fa2e624b1c0ab4f4eb8b03e747a96900b49ac99fa6084ad61972dc6f2b20f0178e6974147

test:
  secret_key_base: 5e4f7178475890a330caa5d0ddac7238c5570c603d511534115ae1098de21263424f25cbaeed48f610088a76e7d2d99eb77e70c1159f490072c5acc4e7604d5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
